name: test

on:
  push:
    branches:
      - main
    paths-ignore:
      - README.md
  pull_request:
    paths-ignore:
      - README.md

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: -Dwarnings

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo test
